/**
 * AmateRS TypeScript SDK
 *
 * This SDK provides TypeScript bindings for AmateRS, a Fully Homomorphic
 * Encrypted Database. It allows you to store and query encrypted data
 * without ever exposing the plaintext to the server.
 *
 * @example
 * ```typescript
 * import { AmateRSClient, Key, CipherBlob } from '@amaters/sdk';
 *
 * // Connect to server
 * const client = await AmateRSClient.connect('http://localhost:50051');
 *
 * // Set a value
 * await client.set('users', Key.fromString('user:123'), CipherBlob.fromBytes(data));
 *
 * // Get a value
 * const value = await client.get('users', Key.fromString('user:123'));
 * ```
 *
 * @packageDocumentation
 */

// Re-export WASM bindings (will be generated by wasm-pack)
// In a real build, these would come from the pkg/ directory

/**
 * Error codes for AmateRS operations
 */
export enum ErrorCode {
  /** Connection error */
  Connection = 1,
  /** Timeout error */
  Timeout = 2,
  /** Invalid argument error */
  InvalidArgument = 3,
  /** Not found error */
  NotFound = 4,
  /** Operation failed error */
  OperationFailed = 5,
  /** Serialization error */
  Serialization = 6,
  /** FHE operation error */
  FheError = 7,
  /** Configuration error */
  Configuration = 8,
  /** Internal error */
  Internal = 9,
  /** Unknown error */
  Unknown = 10,
}

/**
 * AmateRS error type
 */
export interface AmateRSError {
  /** Error code */
  readonly code: ErrorCode;
  /** Error message */
  readonly message: string;
  /** Optional cause */
  readonly cause?: string;
  /** Whether the error is retryable */
  readonly retryable: boolean;
  /** Error code as string */
  codeString(): string;
  /** Convert to JSON */
  toJSON(): string;
}

/**
 * Database key type
 *
 * Keys are immutable byte sequences used to identify data.
 */
export interface Key {
  /** Get the key as bytes */
  toBytes(): Uint8Array;
  /** Get the key as string (lossy conversion) */
  toString(): string;
  /** Key length in bytes */
  readonly length: number;
  /** Check if key is empty */
  isEmpty(): boolean;
  /** Check equality with another key */
  equals(other: Key): boolean;
  /** Compare with another key (-1, 0, 1) */
  compareTo(other: Key): number;
}

/**
 * Key factory functions
 */
export interface KeyConstructor {
  /** Create a key from string */
  fromString(s: string): Key;
  /** Create a key from bytes */
  fromBytes(data: Uint8Array): Key;
  /** Maximum key size (64KB) */
  readonly maxSize: number;
}

/**
 * Encrypted data blob
 *
 * Represents encrypted ciphertext data.
 */
export interface CipherBlob {
  /** Get the ciphertext as bytes */
  toBytes(): Uint8Array;
  /** Ciphertext length in bytes */
  readonly length: number;
  /** Check if blob is empty */
  isEmpty(): boolean;
  /** Verify integrity using checksum */
  verifyIntegrity(): boolean;
  /** Check equality with another blob */
  equals(other: CipherBlob): boolean;
}

/**
 * CipherBlob factory functions
 */
export interface CipherBlobConstructor {
  /** Create a cipher blob from bytes */
  fromBytes(data: Uint8Array): CipherBlob;
  /** Maximum blob size (1GB) */
  readonly maxSize: number;
}

/**
 * Column reference for query building
 */
export interface ColumnRef {
  /** Column name */
  readonly name: string;
}

/**
 * Client configuration options
 */
export interface ClientConfig {
  /** Server address */
  serverAddr: string;
  /** Connection timeout in milliseconds */
  readonly connectTimeoutMs: number;
  /** Request timeout in milliseconds */
  readonly requestTimeoutMs: number;
  /** Maximum connections in pool */
  readonly maxConnections: number;
  /** Maximum retry attempts */
  readonly maxRetries: number;
  /** Initial retry backoff in milliseconds */
  readonly initialBackoffMs: number;

  /** Set connection timeout */
  withConnectTimeout(timeoutMs: number): ClientConfig;
  /** Set request timeout */
  withRequestTimeout(timeoutMs: number): ClientConfig;
  /** Set max connections */
  withMaxConnections(max: number): ClientConfig;
  /** Set max retries */
  withMaxRetries(max: number): ClientConfig;
  /** Set initial backoff */
  withInitialBackoff(backoffMs: number): ClientConfig;
  /** Convert to plain object */
  toObject(): Record<string, unknown>;
}

/**
 * ClientConfig factory
 */
export interface ClientConfigConstructor {
  new (serverAddr: string): ClientConfig;
  /** Create from plain object */
  fromObject(obj: Record<string, unknown>): ClientConfig;
}

/**
 * Connection pool statistics
 */
export interface PoolStats {
  /** Total connections in pool */
  readonly totalConnections: number;
  /** Idle connections */
  readonly idleConnections: number;
  /** Active connections */
  readonly activeConnections: number;
  /** Convert to plain object */
  toObject(): Record<string, unknown>;
}

/**
 * Key-value pair for query results
 */
export interface KeyValuePair {
  /** The key */
  readonly key: Key;
  /** The value */
  readonly value: CipherBlob;
}

/**
 * Query result type
 */
export interface QueryResult {
  /** Check if this is a single value result */
  isSingle(): boolean;
  /** Check if this is a multi-value result */
  isMulti(): boolean;
  /** Check if this is a success result */
  isSuccess(): boolean;
  /** Get the single value (if applicable) */
  readonly value: CipherBlob | null;
  /** Get item count (for multi-value results) */
  readonly itemCount: number;
  /** Get affected rows (for success results) */
  readonly affectedRows: number;
  /** Get item at index */
  getItem(index: number): KeyValuePair | null;
  /** Get all items as array */
  getItems(): KeyValuePair[];
}

/**
 * Predicate type for filtering
 */
export enum PredicateType {
  Eq = 'Eq',
  Gt = 'Gt',
  Lt = 'Lt',
  Gte = 'Gte',
  Lte = 'Lte',
  And = 'And',
  Or = 'Or',
  Not = 'Not',
}

/**
 * Predicate for query filtering
 */
export interface Predicate {
  /** Predicate type */
  readonly predicateType: PredicateType;
  /** Column (if applicable) */
  readonly column?: ColumnRef;
  /** Value (if applicable) */
  readonly value?: CipherBlob;
}

/**
 * Predicate factory functions
 */
export interface PredicateConstructor {
  /** Create equality predicate */
  eq(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create greater than predicate */
  gt(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create less than predicate */
  lt(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create greater than or equal predicate */
  gte(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create less than or equal predicate */
  lte(column: ColumnRef, value: CipherBlob): Predicate;
  /** Create AND predicate */
  and(left: Predicate, right: Predicate): Predicate;
  /** Create OR predicate */
  or(left: Predicate, right: Predicate): Predicate;
  /** Create NOT predicate */
  not(predicate: Predicate): Predicate;
}

/**
 * Update operation type
 */
export enum UpdateType {
  Set = 'Set',
  Add = 'Add',
  Mul = 'Mul',
}

/**
 * Update operation
 */
export interface UpdateOp {
  /** Update type */
  readonly updateType: UpdateType;
  /** Column */
  readonly column: ColumnRef;
  /** Value */
  readonly value: CipherBlob;
}

/**
 * UpdateOp factory functions
 */
export interface UpdateOpConstructor {
  /** Create set update */
  set(column: ColumnRef, value: CipherBlob): UpdateOp;
  /** Create add update (FHE addition) */
  add(column: ColumnRef, value: CipherBlob): UpdateOp;
  /** Create multiply update (FHE multiplication) */
  mul(column: ColumnRef, value: CipherBlob): UpdateOp;
}

/**
 * Query type
 */
export enum QueryType {
  Get = 'get',
  Set = 'set',
  Delete = 'delete',
  Filter = 'filter',
  Update = 'update',
  Range = 'range',
}

/**
 * Query object
 */
export interface Query {
  /** Query type */
  readonly queryType: QueryType;
  /** Collection name */
  readonly collection: string;
  /** Key (if applicable) */
  readonly key?: Key;
  /** Value (if applicable) */
  readonly value?: CipherBlob;
  /** Predicate (if applicable) */
  readonly predicate?: Predicate;
  /** Start key (for range queries) */
  readonly startKey?: Key;
  /** End key (for range queries) */
  readonly endKey?: Key;
  /** Update count */
  readonly updateCount: number;
  /** Get update at index */
  getUpdate(index: number): UpdateOp | null;
}

/**
 * Query builder
 */
export interface QueryBuilder {
  /** Build a Get query */
  get(key: Key): Query;
  /** Build a Set query */
  set(key: Key, value: CipherBlob): Query;
  /** Build a Delete query */
  delete(key: Key): Query;
  /** Build a Filter query */
  filter(predicate: Predicate): Query;
  /** Build a Range query */
  range(start: Key, end: Key): Query;
  /** Start building a where clause */
  whereClause(): PredicateBuilder;
}

/**
 * QueryBuilder factory
 */
export interface QueryBuilderConstructor {
  new (collection: string): QueryBuilder;
}

/**
 * Predicate builder for fluent API
 */
export interface PredicateBuilder {
  /** Create equality filter */
  eq(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create greater than filter */
  gt(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create less than filter */
  lt(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create greater than or equal filter */
  gte(column: ColumnRef, value: CipherBlob): FilterBuilder;
  /** Create less than or equal filter */
  lte(column: ColumnRef, value: CipherBlob): FilterBuilder;
}

/**
 * Filter builder for fluent API
 */
export interface FilterBuilder {
  /** Add AND condition */
  and(other: Predicate): FilterBuilder;
  /** Add OR condition */
  or(other: Predicate): FilterBuilder;
  /** Negate the current predicate */
  not(): FilterBuilder;
  /** Build the filter query */
  build(): Query;
  /** Build an update query */
  update(updates: UpdateOp[]): Query;
  /** Get current predicate */
  readonly predicate: Predicate;
}

/**
 * Batch operation
 */
export interface BatchOperation {
  /** Operation type ('set', 'delete', 'get') */
  readonly type: string;
  /** Collection name */
  readonly collection: string;
  /** Key */
  readonly key: Key;
  /** Value (for set operations) */
  readonly value?: CipherBlob;
  /** Convert to plain object */
  toObject(): Record<string, unknown>;
}

/**
 * BatchOperation factory functions
 */
export interface BatchOperationConstructor {
  /** Create a set operation */
  set(collection: string, key: Key, value: CipherBlob): BatchOperation;
  /** Create a delete operation */
  delete(collection: string, key: Key): BatchOperation;
  /** Create a get operation */
  get(collection: string, key: Key): BatchOperation;
}

/**
 * AmateRS Client interface
 */
export interface AmateRSClient {
  /** Whether the client is connected */
  readonly isConnected: boolean;
  /** Current configuration */
  readonly config: ClientConfig;
  /** Connection pool statistics */
  readonly poolStats: PoolStats;

  /**
   * Set a key-value pair
   * @param collection Collection name
   * @param key Key to set
   * @param value Value to store
   */
  set(collection: string, key: Key, value: CipherBlob): Promise<void>;

  /**
   * Get a value by key
   * @param collection Collection name
   * @param key Key to retrieve
   * @returns The value or null if not found
   */
  get(collection: string, key: Key): Promise<CipherBlob | null>;

  /**
   * Delete a key
   * @param collection Collection name
   * @param key Key to delete
   */
  delete(collection: string, key: Key): Promise<void>;

  /**
   * Check if a key exists
   * @param collection Collection name
   * @param key Key to check
   * @returns True if key exists
   */
  contains(collection: string, key: Key): Promise<boolean>;

  /**
   * Execute a range query
   * @param collection Collection name
   * @param start Start key (inclusive)
   * @param end End key (exclusive)
   * @returns Array of key-value pairs
   */
  range(collection: string, start: Key, end: Key): Promise<KeyValuePair[]>;

  /**
   * Execute a batch of operations
   * @param operations Array of batch operations
   * @returns Array of results
   */
  batch(operations: BatchOperation[]): Promise<unknown[]>;

  /**
   * Execute a query
   * @param query Query to execute
   * @returns Query result
   */
  executeQuery(query: Query): Promise<QueryResult>;

  /**
   * Perform a health check
   * @returns True if server is healthy
   */
  healthCheck(): Promise<boolean>;

  /**
   * Close all connections
   */
  close(): void;

  /**
   * Reconnect to the server
   */
  reconnect(): Promise<void>;
}

/**
 * AmateRSClient factory
 */
export interface AmateRSClientConstructor {
  /**
   * Connect to an AmateRS server
   * @param addr Server address
   * @returns Connected client
   */
  connect(addr: string): Promise<AmateRSClient>;

  /**
   * Connect with custom configuration
   * @param config Client configuration
   * @returns Connected client
   */
  connectWithConfig(config: ClientConfig): Promise<AmateRSClient>;
}

/**
 * Helper function to create a column reference
 * @param name Column name
 * @returns Column reference
 */
export function col(name: string): ColumnRef {
  return { name };
}

/**
 * Helper function to create a query builder
 * @param collection Collection name
 * @returns Query builder
 */
export function query(collection: string): QueryBuilder {
  // This will be implemented by the WASM module
  throw new Error('WASM module not initialized. Call init() first.');
}

/**
 * Get the SDK version
 * @returns SDK version string
 */
export function getVersion(): string {
  return '0.2.0';
}

/**
 * Check if SDK is initialized
 * @returns True if initialized
 */
export function isInitialized(): boolean {
  return false;
}

// Default export with all types and functions
export default {
  ErrorCode,
  PredicateType,
  UpdateType,
  QueryType,
  col,
  query,
  getVersion,
  isInitialized,
};
